title:               Reading Seminar on Positive Geometries
tagline:             'Reading Seminar, Winter 2024'
description:         'A reading seminar at the University of Oregon, organized in Winter Quarter 2024'
show_downloads: true
theme: jekyll-theme-cayman